#----------------------
#\LiteCustomStopServer/
#----------------------
#config.yml
#插件原作者:主世界
#移植作者:梓橙
#本插件已免费发布并在Github上开源

#设置输入/lcss stop后多少秒关服;重启同理
seconds: 60
#设置进入关服/重启倒计时后分别在剩余多少秒时再次发送关服公告
countdown:
  - 50
  - 30
  - 10
  - 5
# 下面两个选项的开关
timing: false
#设置定时关服时间;若不想启用此项请将第一个值设为none
#"是否删除"表示的是该定时关服是否为一次性的,若是则填写1,不是填写0
#格式:'HH-mm,是否删除'
auto_stop_time:
  - '00-00,0'
  - '06-00,0'
  - '20-00,1'
#设置定时重启时间;语法和上一个相同
auto_restart_time:
  - '01-00,0'
  - '05-00,0'
  - '23-00,1'
#设置是否在关服/重启公告发出同时显示Title文字
title_true_or_false: true